spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.162:3306/datamiddleground?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456
#    druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
        max-wait: 60000
        # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u6BEB\u79D2
        time-between-eviction-runs-millis: 60000
        # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u65F6\u95F4
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM user_customer_info
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # \u6253\u5F00 PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0A PSCache \u7684\u5927\u5C0F
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20

## jwt
jwt:
    # \u7B7E\u540D
    signature: xtSoft
    # accessToken\u8FC7\u671F\u65F6\u95F4
    access-expire-time: 1
    # refreshToken\u8FC7\u671F\u65F6\u95F4
    refresh-expire-time: 360
# mybatis-plus\u76F8\u5173\u914D\u7F6E
mybatis-plus:
    configuration:
        # \u662F\u5426\u5F00\u542F\u81EA\u52A8\u9A7C\u5CF0\u547D\u540D\u89C4\u5219\u6620\u5C04:\u4ECE\u6570\u636E\u5E93\u5217\u540D\u5230Java\u5C5E\u6027\u9A7C\u5CF0\u547D\u540D\u7684\u7C7B\u4F3C\u6620\u5C04
        map-underscore-to-camel-case: true
        # \u5982\u679C\u67E5\u8BE2\u7ED3\u679C\u4E2D\u5305\u542B\u7A7A\u503C\u7684\u5217\uFF0C\u5219 MyBatis \u5728\u6620\u5C04\u7684\u65F6\u5019\uFF0C\u4E0D\u4F1A\u6620\u5C04\u8FD9\u4E2A\u5B57\u6BB5
        call-setters-on-nulls: true
